### PR TITLE
Removes POST from /parse

### LINKED ISSUE #12: Remove POST for /parse
`GET` and `POST` for `/parse` currently do exactly the same thing.  There's no real reason to keep around `POST` as it just adds unnecessary complexity.

We may bring back `POST` if/when we decide to support batch parsing, but that will likely be a different resource from `/parse` anyway.

### PR DESCRIPTION
**Pull request by hkeeler**
Closes #12.

This is dependent on #7.  Please review/merge that one first.

### CODE REVIEW

**Comment by wpears** [comment]
References to POST need to be pulled out of the README to keep it in sync.

**Comment by wpears** [comment]
Which would also be a good time to fix the first line of the **/parse** section

```
The /parse resource is the heart of this API. It parses a free-text address strings into their component parts.
```

Should be have the **a** removed, resulting in:

```
The /parse resource is the heart of this API. It parses free-text address strings into their component parts.
```

**Comment by wpears** [comment]
Also looks like this needs to be rebased off upstream/master.

Though we can merge in https://github.com/cfpb/grasshopper-parser/pull/10 first so we don't have to possibly rebase twice.

**Comment by wpears** [comment]
:+1: An preference on on whether this gets merged before #10 now?

**Comment by hkeeler** [comment]
Nice, +2.78% coverage by removing code.  I should remove more until I get to 100%. :)

Nope.  Shouldn't matter if we merge this before #10.  Merge away.

**Pull request merged**
